//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace KK.DealMaker.Core.Data
{
    [MetadataType(typeof(Metadata))]
    public partial class DA_LOGGING
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "ID")]
            [Required(ErrorMessage = "ID is Required.")]	
            public  System.Guid ID { get; set; }	
            
            [Display(Name = "EVENT")]
            [Required(ErrorMessage = "EVENT is Required.")]
            [StringLength(100, ErrorMessage = "EVENT must be under 100 characters.")]	
            public  string EVENT { get; set; }	
            
            [Display(Name = "TABLE_ NAME")]
            [StringLength(100, ErrorMessage = "TABLE_ NAME must be under 100 characters.")]	
            public  string TABLE_NAME { get; set; }	
            
            [Display(Name = "LOG_ DATE")]
            [Required(ErrorMessage = "LOG_ DATE is Required.")]	
            public  System.DateTime LOG_DATE { get; set; }	
            
            [Display(Name = "RECORD_ID")]	
            public  Nullable<System.Guid> RECORD_ID { get; set; }	
            
            [Display(Name = "LOG_ DETAIL")]	
            public  string LOG_DETAIL { get; set; }	

            #endregion
    
            #region Complex Properties
            
            [Display(Name = "LOG")]
            [Required(ErrorMessage = "LOG is Required.")]
            public  LOG LOG { get; set; }

            #endregion
    
    	}

        #endregion
    }
}
