//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace KK.DealMaker.Core.Data
{
    public partial class DA_LOGIN_AUDIT
    {
        public DA_LOGIN_AUDIT()
        {
            this.LOG = new LOG();
        }
    
        #region Primitive Properties
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> LOGON_DATE { get; set; }
        public string TERMINAL { get; set; }
        public string RESULT { get; set; }
        public Nullable<System.DateTime> LOGOUT_DATE { get; set; }
        public System.Guid USER_ID { get; set; }

        #endregion
    
        #region Complex Properties
        public LOG LOG { get; set; }

        #endregion
    }
    
}
