//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace KK.DealMaker.Core.Data
{
    [MetadataType(typeof(Metadata))]
    public partial class DA_LOGIN_AUDIT
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "ID")]
            [Required(ErrorMessage = "ID is Required.")]	
            public  System.Guid ID { get; set; }	
            
            [Display(Name = "LOGON_ DATE")]	
            public  Nullable<System.DateTime> LOGON_DATE { get; set; }	
            
            [Display(Name = "TERMINAL")]
            [StringLength(50, ErrorMessage = "TERMINAL must be under 50 characters.")]	
            public  string TERMINAL { get; set; }	
            
            [Display(Name = "RESULT")]
            [StringLength(200, ErrorMessage = "RESULT must be under 200 characters.")]	
            public  string RESULT { get; set; }	
            
            [Display(Name = "LOGOUT_ DATE")]	
            public  Nullable<System.DateTime> LOGOUT_DATE { get; set; }	
            
            [Display(Name = "USER_ID")]
            [Required(ErrorMessage = "USER_ID is Required.")]	
            public  System.Guid USER_ID { get; set; }	

            #endregion
    
            #region Complex Properties
            
            [Display(Name = "LOG")]
            [Required(ErrorMessage = "LOG is Required.")]
            public  LOG LOG { get; set; }

            #endregion
    
    	}

        #endregion
    }
}
