//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace KK.DealMaker.Core.Data
{
    [MetadataType(typeof(Metadata))]
    public partial class DA_TMBA_EXTENSION
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "ID")]
            [Required(ErrorMessage = "ID is Required.")]	
            public  System.Guid ID { get; set; }	
            
            [Display(Name = "PURPOSE")]
            [Required(ErrorMessage = "PURPOSE is Required.")]
            [StringLength(5, ErrorMessage = "PURPOSE must be under 5 characters.")]	
            public  string PURPOSE { get; set; }	
            
            [Display(Name = "YIELD_ TYPE")]
            [Required(ErrorMessage = "YIELD_ TYPE is Required.")]
            [StringLength(3, ErrorMessage = "YIELD_ TYPE must be under 3 characters.")]	
            public  string YIELD_TYPE { get; set; }	
            
            [Display(Name = "CLEAN_ PRICE")]
            [Required(ErrorMessage = "CLEAN_ PRICE is Required.")]	
            public  decimal CLEAN_PRICE { get; set; }	
            
            [Display(Name = "GROSS_ PRICE")]
            [Required(ErrorMessage = "GROSS_ PRICE is Required.")]	
            public  decimal GROSS_PRICE { get; set; }	
            
            [Display(Name = "UNIT")]
            [Required(ErrorMessage = "UNIT is Required.")]	
            public  int UNIT { get; set; }	
            
            [Display(Name = "TERM")]	
            public  Nullable<int> TERM { get; set; }	
            
            [Display(Name = "RATE")]	
            public  Nullable<decimal> RATE { get; set; }	
            
            [Display(Name = "REMARK")]
            [StringLength(30, ErrorMessage = "REMARK must be under 30 characters.")]	
            public  string REMARK { get; set; }	
            
            [Display(Name = "SENDER_ID")]	
            public  Nullable<System.Guid> SENDER_ID { get; set; }	
            
            [Display(Name = "SEND_ DATE")]	
            public  Nullable<System.DateTime> SEND_DATE { get; set; }	
            
            [Display(Name = "IS_ REPORT_ CLEAN")]
            [Required(ErrorMessage = "IS_ REPORT_ CLEAN is Required.")]	
            public  bool IS_REPORT_CLEAN { get; set; }	

            #endregion
    
    
    	}

        #endregion
    }
}
