//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace KK.DealMaker.Core.Data
{
    [MetadataType(typeof(Metadata))]
    public partial class DA_TRN_MATCH
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "ID")]
            [Required(ErrorMessage = "ID is Required.")]	
            public  System.Guid ID { get; set; }	
            
            [Display(Name = "INT_TRN_ID")]
            [Required(ErrorMessage = "INT_TRN_ID is Required.")]	
            public  System.Guid INT_TRN_ID { get; set; }	
            
            [Display(Name = "EXT_TRN_ID")]
            [Required(ErrorMessage = "EXT_TRN_ID is Required.")]
            [StringLength(50, ErrorMessage = "EXT_TRN_ID must be under 50 characters.")]	
            public  string EXT_TRN_ID { get; set; }	
            
            [Display(Name = "STATUS_ID")]
            [Required(ErrorMessage = "STATUS_ID is Required.")]	
            public  System.Guid STATUS_ID { get; set; }	

            #endregion
    
            #region Complex Properties
            
            [Display(Name = "LOG")]
            [Required(ErrorMessage = "LOG is Required.")]
            public  LOG LOG { get; set; }

            #endregion
    
    	}

        #endregion
    }
}
