//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace KK.DealMaker.Core.Data
{
    [MetadataType(typeof(Metadata))]
    public partial class DA_TRN_CASHFLOW
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "ID")]
            [Required(ErrorMessage = "ID is Required.")]	
            public  System.Guid ID { get; set; }	
            
            [Display(Name = "DA_TRN_ID")]
            [Required(ErrorMessage = "DA_TRN_ID is Required.")]	
            public  System.Guid DA_TRN_ID { get; set; }	
            
            [Display(Name = "SEQ")]
            [Required(ErrorMessage = "SEQ is Required.")]	
            public  int SEQ { get; set; }	
            
            [Display(Name = "RATE")]	
            public  Nullable<decimal> RATE { get; set; }	
            
            [Display(Name = "FLOW_ DATE")]	
            public  Nullable<System.DateTime> FLOW_DATE { get; set; }	
            
            [Display(Name = "FLOW_ AMOUNT")]	
            public  Nullable<decimal> FLOW_AMOUNT { get; set; }	
            
            [Display(Name = "FLAG_ FIRST")]
            [Required(ErrorMessage = "FLAG_ FIRST is Required.")]	
            public  bool FLAG_FIRST { get; set; }	
            
            [Display(Name = "FLOW_ AMOUNT_ THB")]	
            public  Nullable<decimal> FLOW_AMOUNT_THB { get; set; }	

            #endregion
    
            #region Complex Properties
            
            [Display(Name = "LOG")]
            [Required(ErrorMessage = "LOG is Required.")]
            public  LOG LOG { get; set; }

            #endregion
    
            #region Navigation Properties
            	
            public  DA_TRN DA_TRN { get; set; }

            #endregion
    	}

        #endregion
    }
}
