//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace KK.DealMaker.Core.Data
{
    [MetadataType(typeof(Metadata))]
    public partial class LOG
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "INSERTBYUSERID")]
            [Required(ErrorMessage = "INSERTBYUSERID is Required.")]
            public System.Guid INSERTBYUSERID { get; set; }
            
            [Display(Name = "INSERTDATE")]
            [Required(ErrorMessage = "INSERTDATE is Required.")]
            public System.DateTime INSERTDATE { get; set; }
            
            [Display(Name = "MODIFYBYUSERID")]
            public Nullable<System.Guid> MODIFYBYUSERID { get; set; }
            
            [Display(Name = "MODIFYDATE")]
            public Nullable<System.DateTime> MODIFYDATE { get; set; }

            #endregion
    	}

        #endregion
    }
}
