//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace KK.DealMaker.Core.Data
{
    public partial class MA_CTPY_LIMIT
    {
        public MA_CTPY_LIMIT()
        {
            this.MA_TEMP_CTPY_LIMIT = new HashSet<MA_TEMP_CTPY_LIMIT>();
            this.LOG = new LOG();
        }
    
        #region Primitive Properties
        public System.Guid ID { get; set; }
        public bool FLAG_CONTROL { get; set; }
        public decimal AMOUNT { get; set; }
        public System.DateTime EXPIRE_DATE { get; set; }
        public System.Guid CTPY_ID { get; set; }
        public System.Guid LIMIT_ID { get; set; }

        #endregion
    
        #region Complex Properties
        public LOG LOG { get; set; }

        #endregion
    
        #region Navigation Properties
        public ICollection<MA_TEMP_CTPY_LIMIT> MA_TEMP_CTPY_LIMIT { get; set; }
        public MA_LIMIT MA_LIMIT { get; set; }

        #endregion
    }
    
}
