//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace KK.DealMaker.Core.Data
{
    public partial class MA_CURRENCY
    {
        #region Primitive Properties
        public System.Guid ID { get; set; }
        public string LABEL { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }

        #endregion
    }
    
}
