//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace KK.DealMaker.Core.Data
{
    [MetadataType(typeof(Metadata))]
    public partial class MA_CONFIG_ATTRIBUTE
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "TABLE")]
            [Required(ErrorMessage = "TABLE is Required.")]
            [StringLength(100, ErrorMessage = "TABLE must be under 100 characters.")]	
            public  string TABLE { get; set; }	
            
            [Display(Name = "ATTRIBUTE")]
            [StringLength(100, ErrorMessage = "ATTRIBUTE must be under 100 characters.")]	
            public  string ATTRIBUTE { get; set; }	
            
            [Display(Name = "VALUE")]
            [StringLength(200, ErrorMessage = "VALUE must be under 200 characters.")]	
            public  string VALUE { get; set; }	
            
            [Display(Name = "ID")]
            [Required(ErrorMessage = "ID is Required.")]	
            public  System.Guid ID { get; set; }	
            
            [Display(Name = "ISACTIVE")]
            [Required(ErrorMessage = "ISACTIVE is Required.")]	
            public  bool ISACTIVE { get; set; }	
            
            [Display(Name = "PCCF_CONFIG_ID")]
            [Required(ErrorMessage = "PCCF_CONFIG_ID is Required.")]	
            public  System.Guid PCCF_CONFIG_ID { get; set; }	

            #endregion
    
            #region Complex Properties
            
            [Display(Name = "LOG")]
            [Required(ErrorMessage = "LOG is Required.")]
            public  LOG LOG { get; set; }

            #endregion
    
    	}

        #endregion
    }
}
