//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace KK.DealMaker.Core.Data
{
    [MetadataType(typeof(Metadata))]
    public partial class MA_CSA_AGREEMENT
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "ID")]
            [Required(ErrorMessage = "ID is Required.")]	
            public  System.Guid ID { get; set; }	
            
            [Display(Name = "CSA_TYPE_ID")]	
            public  Nullable<System.Guid> CSA_TYPE_ID { get; set; }	
            
            [Display(Name = "ISACTIVE")]
            [Required(ErrorMessage = "ISACTIVE is Required.")]	
            public  bool ISACTIVE { get; set; }	

            #endregion
    
            #region Complex Properties
            
            [Display(Name = "LOG")]
            [Required(ErrorMessage = "LOG is Required.")]
            public  LOG LOG { get; set; }

            #endregion
    
            #region Navigation Properties
            	
            public  MA_CSA_TYPE MA_CSA_TYPE { get; set; }
            	
            public  ICollection<MA_CSA_PRODUCT> MA_CSA_PRODUCT { get; set; }

            #endregion
    	}

        #endregion
    }
}
