//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace KK.DealMaker.Core.Data
{
    public partial class MA_CSA_PRODUCT
    {
        #region Primitive Properties
        public System.Guid CSA_AGREEMENT_ID { get; set; }
        public System.Guid PRODUCT_ID { get; set; }

        #endregion
    
        #region Navigation Properties
        public MA_PRODUCT MA_PRODUCT { get; set; }

        #endregion
    }
    
}
