//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace KK.DealMaker.Core.Data
{
    [MetadataType(typeof(Metadata))]
    public partial class MA_INSTRUMENT
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "ID")]
            [Required(ErrorMessage = "ID is Required.")]	
            public  System.Guid ID { get; set; }	
            
            [Display(Name = "LABEL")]
            [Required(ErrorMessage = "LABEL is Required.")]
            [StringLength(50, ErrorMessage = "LABEL must be under 50 characters.")]	
            public  string LABEL { get; set; }	
            
            [Display(Name = "ISSUER")]
            [StringLength(50, ErrorMessage = "ISSUER must be under 50 characters.")]	
            public  string ISSUER { get; set; }	
            
            [Display(Name = "LOT_ SIZE")]	
            public  Nullable<int> LOT_SIZE { get; set; }	
            
            [Display(Name = "COUPON")]	
            public  Nullable<decimal> COUPON { get; set; }	
            
            [Display(Name = "MATURITY_ DATE")]	
            public  Nullable<System.DateTime> MATURITY_DATE { get; set; }	
            
            [Display(Name = "CAL_ METHOD")]
            [StringLength(50, ErrorMessage = "CAL_ METHOD must be under 50 characters.")]	
            public  string CAL_METHOD { get; set; }	
            
            [Display(Name = "ISACTIVE")]
            [Required(ErrorMessage = "ISACTIVE is Required.")]	
            public  bool ISACTIVE { get; set; }	
            
            [Display(Name = "PRODUCT_ID")]
            [Required(ErrorMessage = "PRODUCT_ID is Required.")]	
            public  System.Guid PRODUCT_ID { get; set; }	
            
            [Display(Name = "FLAG_ FIXED")]	
            public  Nullable<bool> FLAG_FIXED { get; set; }	
            
            [Display(Name = "COUPON_FREQ_TYPE_ID")]	
            public  Nullable<System.Guid> COUPON_FREQ_TYPE_ID { get; set; }	
            
            [Display(Name = "INS_ MKT")]	
            public  Nullable<System.Guid> INS_MKT { get; set; }	
            
            [Display(Name = "FLAG_ MULTIPLY")]	
            public  Nullable<bool> FLAG_MULTIPLY { get; set; }	
            
            [Display(Name = "CURRENCY_ID1")]	
            public  Nullable<System.Guid> CURRENCY_ID1 { get; set; }	
            
            [Display(Name = "CURRENCY_ID2")]	
            public  Nullable<System.Guid> CURRENCY_ID2 { get; set; }	

            #endregion
    
            #region Complex Properties
            
            [Display(Name = "LOG")]
            [Required(ErrorMessage = "LOG is Required.")]
            public  LOG LOG { get; set; }

            #endregion
    
            #region Navigation Properties
            	
            public  ICollection<DA_TRN> DA_TRN { get; set; }
            	
            public  MA_PRODUCT MA_PRODUCT { get; set; }
            	
            public  MA_FREQ_TYPE MA_FREQ_TYPE { get; set; }
            	
            public  MA_BOND_MARKET MA_BOND_MARKET { get; set; }
            	
            public  MA_CURRENCY MA_CURRENCY { get; set; }
            	
            public  MA_CURRENCY MA_CURRENCY2 { get; set; }

            #endregion
    	}

        #endregion
    }
}
