//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace KK.DealMaker.Core.Data
{
    public partial class MA_LIMIT
    {
        public MA_LIMIT()
        {
            this.MA_LIMIT_PRODUCT = new HashSet<MA_LIMIT_PRODUCT>();
        }
    
        #region Primitive Properties
        public System.Guid ID { get; set; }
        public string LABEL { get; set; }
        public bool ISACTIVE { get; set; }
        public string LIMIT_TYPE { get; set; }
        public Nullable<int> INDEX { get; set; }

        #endregion
    
        #region Navigation Properties
        public ICollection<MA_LIMIT_PRODUCT> MA_LIMIT_PRODUCT { get; set; }

        #endregion
    }
    
}
