//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace KK.DealMaker.Core.Data
{
    [MetadataType(typeof(Metadata))]
    public partial class MA_PCCF_CONFIG
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "ID")]
            [Required(ErrorMessage = "ID is Required.")]	
            public  System.Guid ID { get; set; }	
            
            [Display(Name = "LABEL")]
            [Required(ErrorMessage = "LABEL is Required.")]
            [StringLength(50, ErrorMessage = "LABEL must be under 50 characters.")]	
            public  string LABEL { get; set; }	
            
            [Display(Name = "DESCRIPTION")]
            [StringLength(255, ErrorMessage = "DESCRIPTION must be under 255 characters.")]	
            public  string DESCRIPTION { get; set; }	
            
            [Display(Name = "PRODUCT_ID")]
            [Required(ErrorMessage = "PRODUCT_ID is Required.")]	
            public  System.Guid PRODUCT_ID { get; set; }	
            
            [Display(Name = "PCCF_ID")]
            [Required(ErrorMessage = "PCCF_ID is Required.")]	
            public  System.Guid PCCF_ID { get; set; }	
            
            [Display(Name = "ISACTIVE")]	
            public  Nullable<bool> ISACTIVE { get; set; }	
            
            [Display(Name = "PRIORITY")]	
            public  Nullable<int> PRIORITY { get; set; }	

            #endregion
    
            #region Complex Properties
            
            [Display(Name = "LOG")]
            [Required(ErrorMessage = "LOG is Required.")]
            public  LOG LOG { get; set; }

            #endregion
    
            #region Navigation Properties
            	
            public  MA_PCCF MA_PCCF { get; set; }
            	
            public  ICollection<MA_CONFIG_ATTRIBUTE> MA_CONFIG_ATTRIBUTE { get; set; }

            #endregion
    	}

        #endregion
    }
}
