//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace KK.DealMaker.Core.Data
{
    public partial class MA_PRODUCT
    {
        public MA_PRODUCT()
        {
            this.MA_LIMIT_PRODUCT = new HashSet<MA_LIMIT_PRODUCT>();
            this.MA_INSRUMENT = new HashSet<MA_INSTRUMENT>();
            this.MA_PCCF_CONFIG = new HashSet<MA_PCCF_CONFIG>();
        }
    
        #region Primitive Properties
        public System.Guid ID { get; set; }
        public string LABEL { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }

        #endregion
    
        #region Navigation Properties
        public ICollection<MA_LIMIT_PRODUCT> MA_LIMIT_PRODUCT { get; set; }
        public ICollection<MA_INSTRUMENT> MA_INSRUMENT { private get; set; }
        public ICollection<MA_PCCF_CONFIG> MA_PCCF_CONFIG { get; set; }

        #endregion
    }
    
}
