//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace KK.DealMaker.Core.Data
{
    [MetadataType(typeof(Metadata))]
    public partial class MA_PROCESS_DATE
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "PROC_ DATE")]
            [Required(ErrorMessage = "PROC_ DATE is Required.")]	
            public  System.DateTime PROC_DATE { get; set; }	
            
            [Display(Name = "PREV_ PROC_ DATE")]
            [Required(ErrorMessage = "PREV_ PROC_ DATE is Required.")]	
            public  System.DateTime PREV_PROC_DATE { get; set; }	
            
            [Display(Name = "NEXT_ PROC_ DATE")]
            [Required(ErrorMessage = "NEXT_ PROC_ DATE is Required.")]	
            public  System.DateTime NEXT_PROC_DATE { get; set; }	
            
            [Display(Name = "FLAG_ RECONCILE")]	
            public  Nullable<bool> FLAG_RECONCILE { get; set; }	

            #endregion
    
            #region Complex Properties
            
            [Display(Name = "LOG")]
            [Required(ErrorMessage = "LOG is Required.")]
            public  LOG LOG { get; set; }

            #endregion
    
    	}

        #endregion
    }
}
