//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace KK.DealMaker.Core.Data
{
    [MetadataType(typeof(Metadata))]
    public partial class MA_PCCF
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "ID")]
            [Required(ErrorMessage = "ID is Required.")]	
            public  System.Guid ID { get; set; }	
            
            [Display(Name = "LABEL")]
            [Required(ErrorMessage = "LABEL is Required.")]
            [StringLength(50, ErrorMessage = "LABEL must be under 50 characters.")]	
            public  string LABEL { get; set; }	
            
            [Display(Name = "C1")]	
            public  Nullable<decimal> C1 { get; set; }	
            
            [Display(Name = "C2")]	
            public  Nullable<decimal> C2 { get; set; }	
            
            [Display(Name = "C3")]	
            public  Nullable<decimal> C3 { get; set; }	
            
            [Display(Name = "C4")]	
            public  Nullable<decimal> C4 { get; set; }	
            
            [Display(Name = "C5")]	
            public  Nullable<decimal> C5 { get; set; }	
            
            [Display(Name = "C6")]	
            public  Nullable<decimal> C6 { get; set; }	
            
            [Display(Name = "C7")]	
            public  Nullable<decimal> C7 { get; set; }	
            
            [Display(Name = "C8")]	
            public  Nullable<decimal> C8 { get; set; }	
            
            [Display(Name = "C9")]	
            public  Nullable<decimal> C9 { get; set; }	
            
            [Display(Name = "C10")]	
            public  Nullable<decimal> C10 { get; set; }	
            
            [Display(Name = "C11")]	
            public  Nullable<decimal> C11 { get; set; }	
            
            [Display(Name = "C12")]	
            public  Nullable<decimal> C12 { get; set; }	
            
            [Display(Name = "C13")]	
            public  Nullable<decimal> C13 { get; set; }	
            
            [Display(Name = "C14")]	
            public  Nullable<decimal> C14 { get; set; }	
            
            [Display(Name = "C15")]	
            public  Nullable<decimal> C15 { get; set; }	
            
            [Display(Name = "C16")]	
            public  Nullable<decimal> C16 { get; set; }	
            
            [Display(Name = "C17")]	
            public  Nullable<decimal> C17 { get; set; }	
            
            [Display(Name = "C18")]	
            public  Nullable<decimal> C18 { get; set; }	
            
            [Display(Name = "C19")]	
            public  Nullable<decimal> C19 { get; set; }	
            
            [Display(Name = "C20")]	
            public  Nullable<decimal> C20 { get; set; }	
            
            [Display(Name = "More20")]	
            public  Nullable<decimal> more20 { get; set; }	
            
            [Display(Name = "DEFAULT")]	
            public  Nullable<decimal> DEFAULT { get; set; }	
            
            [Display(Name = "ISACTIVE")]	
            public  Nullable<bool> ISACTIVE { get; set; }	
            
            [Display(Name = "C0 D")]	
            public  Nullable<decimal> C0D { get; set; }	
            
            [Display(Name = "C1 D")]	
            public  Nullable<decimal> C1D { get; set; }	
            
            [Display(Name = "C21")]	
            public  Nullable<decimal> C21 { get; set; }	
            
            [Display(Name = "C22")]	
            public  Nullable<decimal> C22 { get; set; }	
            
            [Display(Name = "C23")]	
            public  Nullable<decimal> C23 { get; set; }	
            
            [Display(Name = "C24")]	
            public  Nullable<decimal> C24 { get; set; }	

            #endregion
    
            #region Complex Properties
            
            [Display(Name = "LOG")]
            [Required(ErrorMessage = "LOG is Required.")]
            public  LOG LOG { get; set; }

            #endregion
    
    	}

        #endregion
    }
}
