//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace KK.DealMaker.Core.Data
{
    [MetadataType(typeof(Metadata))]
    public partial class MA_PROFILE_FUNCTIONAL
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "ISREADABLE")]
            [Required(ErrorMessage = "ISREADABLE is Required.")]	
            public  bool ISREADABLE { get; set; }	
            
            [Display(Name = "ISWRITABLE")]
            [Required(ErrorMessage = "ISWRITABLE is Required.")]	
            public  bool ISWRITABLE { get; set; }	
            
            [Display(Name = "ID")]
            [Required(ErrorMessage = "ID is Required.")]	
            public  System.Guid ID { get; set; }	
            
            [Display(Name = "ISAPPROVABLE")]
            [Required(ErrorMessage = "ISAPPROVABLE is Required.")]	
            public  bool ISAPPROVABLE { get; set; }	
            
            [Display(Name = "FUNCTIONAL_ID")]
            [Required(ErrorMessage = "FUNCTIONAL_ID is Required.")]	
            public  System.Guid FUNCTIONAL_ID { get; set; }	
            
            [Display(Name = "USER_PROFILE_ID")]
            [Required(ErrorMessage = "USER_PROFILE_ID is Required.")]	
            public  System.Guid USER_PROFILE_ID { get; set; }	

            #endregion
    
    
            #region Navigation Properties
            	
            public  MA_FUNCTIONAL MA_FUNCTIONAL { get; set; }
            	
            public  MA_USER_PROFILE MA_USER_PROFILE { get; set; }

            #endregion
    	}

        #endregion
    }
}
