//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace KK.DealMaker.Core.Data
{
    public partial class MA_PROFILE_FUNCTIONAL
    {
        #region Primitive Properties
        public bool ISREADABLE { get; set; }
        public bool ISWRITABLE { get; set; }
        public System.Guid ID { get; set; }
        public bool ISAPPROVABLE { get; set; }
        public System.Guid FUNCTIONAL_ID { get; set; }
        public System.Guid USER_PROFILE_ID { get; set; }

        #endregion
    
        #region Navigation Properties
        public MA_FUNCTIONAL MA_FUNCTIONAL { get; set; }
        public MA_USER_PROFILE MA_USER_PROFILE { get; set; }

        #endregion
    }
    
}
