//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace KK.DealMaker.Core.Data
{
    public partial class MA_PCCF
    {
        public MA_PCCF()
        {
            this.LOG = new LOG();
        }
    
        #region Primitive Properties
        public System.Guid ID { get; set; }
        public string LABEL { get; set; }
        public Nullable<decimal> C1 { get; set; }
        public Nullable<decimal> C2 { get; set; }
        public Nullable<decimal> C3 { get; set; }
        public Nullable<decimal> C4 { get; set; }
        public Nullable<decimal> C5 { get; set; }
        public Nullable<decimal> C6 { get; set; }
        public Nullable<decimal> C7 { get; set; }
        public Nullable<decimal> C8 { get; set; }
        public Nullable<decimal> C9 { get; set; }
        public Nullable<decimal> C10 { get; set; }
        public Nullable<decimal> C11 { get; set; }
        public Nullable<decimal> C12 { get; set; }
        public Nullable<decimal> C13 { get; set; }
        public Nullable<decimal> C14 { get; set; }
        public Nullable<decimal> C15 { get; set; }
        public Nullable<decimal> C16 { get; set; }
        public Nullable<decimal> C17 { get; set; }
        public Nullable<decimal> C18 { get; set; }
        public Nullable<decimal> C19 { get; set; }
        public Nullable<decimal> C20 { get; set; }
        public Nullable<decimal> more20 { get; set; }
        public Nullable<decimal> DEFAULT { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<decimal> C0D { get; set; }
        public Nullable<decimal> C1D { get; set; }
        public Nullable<decimal> C21 { get; set; }
        public Nullable<decimal> C22 { get; set; }
        public Nullable<decimal> C23 { get; set; }
        public Nullable<decimal> C24 { get; set; }

        #endregion
    
        #region Complex Properties
        public LOG LOG { get; set; }

        #endregion
    }
    
}
