//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace KK.DealMaker.Core.Data
{
    public partial class MA_SPOT_RATE
    {
        #region Primitive Properties
        public System.Guid ID { get; set; }
        public System.Guid CURRENCY_ID { get; set; }
        public System.DateTime PROC_DATE { get; set; }
        public decimal RATE { get; set; }

        #endregion
    
        #region Navigation Properties
        public MA_CURRENCY MA_CURRENCY { get; set; }

        #endregion
    }
    
}
