//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace KK.DealMaker.Core.Data
{
    [MetadataType(typeof(Metadata))]
    public partial class MA_TBMA_CONFIG
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "TBMA_ CAL_ USERNAME")]
            [Required(ErrorMessage = "TBMA_ CAL_ USERNAME is Required.")]
            [StringLength(50, ErrorMessage = "TBMA_ CAL_ USERNAME must be under 50 characters.")]	
            public  string TBMA_CAL_USERNAME { get; set; }	
            
            [Display(Name = "TBMA_ CAL_ PASSWORD")]
            [Required(ErrorMessage = "TBMA_ CAL_ PASSWORD is Required.")]
            [StringLength(50, ErrorMessage = "TBMA_ CAL_ PASSWORD must be under 50 characters.")]	
            public  string TBMA_CAL_PASSWORD { get; set; }	
            
            [Display(Name = "TBMA_ CAL_ IP")]
            [Required(ErrorMessage = "TBMA_ CAL_ IP is Required.")]
            [StringLength(50, ErrorMessage = "TBMA_ CAL_ IP must be under 50 characters.")]	
            public  string TBMA_CAL_IP { get; set; }	
            
            [Display(Name = "TBMA_ RPT_ PATH")]
            [Required(ErrorMessage = "TBMA_ RPT_ PATH is Required.")]
            [StringLength(200, ErrorMessage = "TBMA_ RPT_ PATH must be under 200 characters.")]	
            public  string TBMA_RPT_PATH { get; set; }	
            
            [Display(Name = "TBMA_ RPT_ PREFIX")]
            [Required(ErrorMessage = "TBMA_ RPT_ PREFIX is Required.")]
            [StringLength(50, ErrorMessage = "TBMA_ RPT_ PREFIX must be under 50 characters.")]	
            public  string TBMA_RPT_PREFIX { get; set; }	
            
            [Display(Name = "TBMA_RPT_TRADERID")]
            [Required(ErrorMessage = "TBMA_RPT_TRADERID is Required.")]
            [StringLength(50, ErrorMessage = "TBMA_RPT_TRADERID must be under 50 characters.")]	
            public  string TBMA_RPT_TRADERID { get; set; }	
            
            [Display(Name = "ID")]
            [Required(ErrorMessage = "ID is Required.")]	
            public  System.Guid ID { get; set; }	

            #endregion
    
    
    	}

        #endregion
    }
}
