//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace KK.DealMaker.Core.Data
{
    public partial class MA_TBMA_CONFIG
    {
        #region Primitive Properties
        public string TBMA_CAL_USERNAME { get; set; }
        public string TBMA_CAL_PASSWORD { get; set; }
        public string TBMA_CAL_IP { get; set; }
        public string TBMA_RPT_PATH { get; set; }
        public string TBMA_RPT_PREFIX { get; set; }
        public string TBMA_RPT_TRADERID { get; set; }
        public System.Guid ID { get; set; }

        #endregion
    }
    
}
