//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace KK.DealMaker.Core.Data
{
    [MetadataType(typeof(Metadata))]
    public partial class MA_USER
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "ID")]
            [Required(ErrorMessage = "ID is Required.")]	
            public  System.Guid ID { get; set; }	
            
            [Display(Name = "USERCODE")]
            [Required(ErrorMessage = "USERCODE is Required.")]
            [StringLength(50, ErrorMessage = "USERCODE must be under 50 characters.")]	
            public  string USERCODE { get; set; }	
            
            [Display(Name = "NAME")]
            [StringLength(200, ErrorMessage = "NAME must be under 200 characters.")]	
            public  string NAME { get; set; }	
            
            [Display(Name = "DEPARTMENT")]
            [StringLength(200, ErrorMessage = "DEPARTMENT must be under 200 characters.")]	
            public  string DEPARTMENT { get; set; }	
            
            [Display(Name = "ISLOCKED")]	
            public  Nullable<bool> ISLOCKED { get; set; }	
            
            [Display(Name = "ISACTIVE")]	
            public  Nullable<bool> ISACTIVE { get; set; }	
            
            [Display(Name = "USER_ OPICS")]
            [Required(ErrorMessage = "USER_ OPICS is Required.")]
            [StringLength(20, ErrorMessage = "USER_ OPICS must be under 20 characters.")]	
            public  string USER_OPICS { get; set; }	
            
            [Display(Name = "USER_PROFILE_ID")]
            [Required(ErrorMessage = "USER_PROFILE_ID is Required.")]	
            public  System.Guid USER_PROFILE_ID { get; set; }	

            #endregion
    
            #region Complex Properties
            
            [Display(Name = "LOG")]
            [Required(ErrorMessage = "LOG is Required.")]
            public  LOG LOG { get; set; }

            #endregion
    
            #region Navigation Properties
            	
            public  MA_USER_PROFILE MA_USER_PROFILE { get; set; }

            #endregion
    	}

        #endregion
    }
}
