//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace KK.DealMaker.Core.Data
{
    public partial class TRN_TYPE
    {
        #region Primitive Properties
        public Nullable<decimal> NOTIONAL { get; set; }
        public Nullable<System.Guid> CCY_ID { get; set; }
        public string FLAG_PAYREC { get; set; }
        public string INDEX { get; set; }
        public Nullable<bool> FLAG_FIXED { get; set; }
        public Nullable<decimal> FIRSTFIXINGAMT { get; set; }
        public Nullable<System.Guid> FREQTYPE_ID { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public Nullable<decimal> SWAP_POINT { get; set; }

        #endregion
    }
    
}
