//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace KK.DealMaker.Core.Data
{
    [MetadataType(typeof(Metadata))]
    public partial class TRN_TYPE
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "NOTIONAL")]
            public Nullable<decimal> NOTIONAL { get; set; }
            
            [Display(Name = "CCY_ID")]
            public Nullable<System.Guid> CCY_ID { get; set; }
            
            [Display(Name = "FLAG_ PAYREC")]
            [StringLength(1, ErrorMessage = "FLAG_ PAYREC must be under 1 characters.")]
            public string FLAG_PAYREC { get; set; }
            
            [Display(Name = "INDEX")]
            [StringLength(50, ErrorMessage = "INDEX must be under 50 characters.")]
            public string INDEX { get; set; }
            
            [Display(Name = "FLAG_ FIXED")]
            public Nullable<bool> FLAG_FIXED { get; set; }
            
            [Display(Name = "FIRSTFIXINGAMT")]
            public Nullable<decimal> FIRSTFIXINGAMT { get; set; }
            
            [Display(Name = "FREQTYPE_ID")]
            public Nullable<System.Guid> FREQTYPE_ID { get; set; }
            
            [Display(Name = "RATE")]
            public Nullable<decimal> RATE { get; set; }
            
            [Display(Name = "SWAP_ POINT")]
            public Nullable<decimal> SWAP_POINT { get; set; }

            #endregion
    	}

        #endregion
    }
}
