//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using KK.DealMaker.Core.Data;

namespace KK.DealMaker.DataAccess
{
    public partial class KKLMDBEntities : DbContext
    {
        public KKLMDBEntities()
            : base("name=KKLMDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DA_LOGIN_AUDIT> DA_LOGIN_AUDIT { get; set; }
        public DbSet<DA_TRN> DA_TRN { get; set; }
        public DbSet<DA_TRN_CASHFLOW> DA_TRN_CASHFLOW { get; set; }
        public DbSet<MA_PORTFOLIO> MA_PORTFOLIO { get; set; }
        public DbSet<MA_PRODUCT> MA_PRODUCT { get; set; }
        public DbSet<MA_STATUS> MA_STATUS { get; set; }
        public DbSet<MA_USER> MA_USER { get; set; }
        public DbSet<MA_COUTERPARTY> MA_COUTERPARTY { get; set; }
        public DbSet<MA_INSTRUMENT> MA_INSTRUMENT { get; set; }
        public DbSet<MA_PCCF> MA_PCCF { get; set; }
        public DbSet<MA_FUNCTIONAL> MA_FUNCTIONAL { get; set; }
        public DbSet<MA_PROFILE_FUNCTIONAL> MA_PROFILE_FUNCTIONAL { get; set; }
        public DbSet<MA_USER_PROFILE> MA_USER_PROFILE { get; set; }
        public DbSet<MA_FREQ_TYPE> MA_FREQ_TYPE { get; set; }
        public DbSet<DA_TRN_MATCH> DA_TRN_MATCH { get; set; }
        public DbSet<MA_LIMIT> MA_LIMIT { get; set; }
        public DbSet<MA_CTPY_LIMIT> MA_CTPY_LIMIT { get; set; }
        public DbSet<MA_LIMIT_PRODUCT> MA_LIMIT_PRODUCT { get; set; }
        public DbSet<DA_LOGGING> DA_LOGGING { get; set; }
        public DbSet<MA_PROCESS_DATE> MA_PROCESS_DATE { get; set; }
        public DbSet<MA_CURRENCY> MA_CURRENCY { get; set; }
        public DbSet<MA_SPOT_RATE> MA_SPOT_RATE { get; set; }
        public DbSet<MA_BOND_MARKET> MA_BOND_MARKET { get; set; }
        public DbSet<MA_PCCF_CONFIG> MA_PCCF_CONFIG { get; set; }
        public DbSet<MA_CONFIG_ATTRIBUTE> MA_CONFIG_ATTRIBUTE { get; set; }
        public DbSet<MA_TEMP_CTPY_LIMIT> MA_TEMP_CTPY_LIMIT { get; set; }
        public DbSet<DA_TMBA_EXTENSION> DA_TMBA_EXTENSION { get; set; }
        public DbSet<MA_COUNTRY> MA_COUNTRY { get; set; }
        public DbSet<MA_COUNTRY_LIMIT> MA_COUNTRY_LIMIT { get; set; }
        public DbSet<MA_CSA_TYPE> MA_CSA_TYPE { get; set; }
        public DbSet<MA_CSA_AGREEMENT> MA_CSA_AGREEMENT { get; set; }
        public DbSet<MA_CSA_PRODUCT> MA_CSA_PRODUCT { get; set; }
        public DbSet<MA_TBMA_CONFIG> MA_TBMA_CONFIG { get; set; }
    }
}
