//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace KK.DealMaker.Web.ThaiBMACalc {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ThaiBMA_Claculation_ServiceSoap", Namespace="http://www.ws1.thaibma.or.th/")]
    public partial class ThaiBMA_Claculation_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthenHeader authenHeaderValueField;
        
        private System.Threading.SendOrPostCallback BondCalculationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ThaiBMA_Claculation_Service() {
            this.Url = global::KK.DealMaker.Web.Properties.Settings.Default.KK_DealMaker_Web_ThaiBMACalc_ThaiBMA_Claculation_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthenHeader AuthenHeaderValue {
            get {
                return this.authenHeaderValueField;
            }
            set {
                this.authenHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BondCalculationCompletedEventHandler BondCalculationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ws1.thaibma.or.th/BondCalculation", RequestNamespace="http://www.ws1.thaibma.or.th/", ResponseNamespace="http://www.ws1.thaibma.or.th/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CalculationOutput BondCalculation(BondFactor bf) {
            object[] results = this.Invoke("BondCalculation", new object[] {
                        bf});
            return ((CalculationOutput)(results[0]));
        }
        
        /// <remarks/>
        public void BondCalculationAsync(BondFactor bf) {
            this.BondCalculationAsync(bf, null);
        }
        
        /// <remarks/>
        public void BondCalculationAsync(BondFactor bf, object userState) {
            if ((this.BondCalculationOperationCompleted == null)) {
                this.BondCalculationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBondCalculationOperationCompleted);
            }
            this.InvokeAsync("BondCalculation", new object[] {
                        bf}, this.BondCalculationOperationCompleted, userState);
        }
        
        private void OnBondCalculationOperationCompleted(object arg) {
            if ((this.BondCalculationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BondCalculationCompleted(this, new BondCalculationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ws1.thaibma.or.th/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ws1.thaibma.or.th/", IsNullable=false)]
    public partial class AuthenHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string keyField;
        
        private string usernameField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ws1.thaibma.or.th/")]
    public partial class ServiceError {
        
        private string errorNoField;
        
        private string errorMessageField;
        
        private System.DateTime timeStampField;
        
        private bool resultField;
        
        /// <remarks/>
        public string ErrorNo {
            get {
                return this.errorNoField;
            }
            set {
                this.errorNoField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        public bool Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ws1.thaibma.or.th/")]
    public partial class CalcError {
        
        private string symbolField;
        
        private string isReOpen_BOTFRNField;
        
        private string isILBField;
        
        private string settlementDateField;
        
        private string tradeDateAndTimeField;
        
        private string yieldField;
        
        private string yieldTypeField;
        
        private string isCallPutOptionField;
        
        private string optionTypeField;
        
        private string optionDateField;
        
        private string unitField;
        
        private string percent_PriceField;
        
        private string priceTypeField;
        
        private string othField;
        
        /// <remarks/>
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string isReOpen_BOTFRN {
            get {
                return this.isReOpen_BOTFRNField;
            }
            set {
                this.isReOpen_BOTFRNField = value;
            }
        }
        
        /// <remarks/>
        public string isILB {
            get {
                return this.isILBField;
            }
            set {
                this.isILBField = value;
            }
        }
        
        /// <remarks/>
        public string SettlementDate {
            get {
                return this.settlementDateField;
            }
            set {
                this.settlementDateField = value;
            }
        }
        
        /// <remarks/>
        public string TradeDateAndTime {
            get {
                return this.tradeDateAndTimeField;
            }
            set {
                this.tradeDateAndTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Yield {
            get {
                return this.yieldField;
            }
            set {
                this.yieldField = value;
            }
        }
        
        /// <remarks/>
        public string YieldType {
            get {
                return this.yieldTypeField;
            }
            set {
                this.yieldTypeField = value;
            }
        }
        
        /// <remarks/>
        public string isCallPutOption {
            get {
                return this.isCallPutOptionField;
            }
            set {
                this.isCallPutOptionField = value;
            }
        }
        
        /// <remarks/>
        public string OptionType {
            get {
                return this.optionTypeField;
            }
            set {
                this.optionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string OptionDate {
            get {
                return this.optionDateField;
            }
            set {
                this.optionDateField = value;
            }
        }
        
        /// <remarks/>
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        public string Percent_Price {
            get {
                return this.percent_PriceField;
            }
            set {
                this.percent_PriceField = value;
            }
        }
        
        /// <remarks/>
        public string PriceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Oth {
            get {
                return this.othField;
            }
            set {
                this.othField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ws1.thaibma.or.th/")]
    public partial class CalcResult {
        
        private string symbolField;
        
        private System.DateTime settlementDateField;
        
        private System.DateTime tradeDateAndTimeField;
        
        private int unitField;
        
        private System.Nullable<double> percent_YieldField;
        
        private System.Nullable<double> percent_YSField;
        
        private System.Nullable<double> percent_DMField;
        
        private System.Nullable<double> percent_GrossPriceField;
        
        private System.Nullable<double> percent_CleanPriceField;
        
        private System.Nullable<double> percent_AIField;
        
        private System.Nullable<double> tHB_GrossValueField;
        
        private System.Nullable<double> tHB_CleanValueField;
        
        private System.Nullable<double> tHB_AIValueField;
        
        private System.Nullable<double> dSCField;
        
        private System.Nullable<double> dCSField;
        
        private System.Nullable<double> percent_IField;
        
        private System.Nullable<double> pVBPField;
        
        private System.Nullable<double> yr_MacaulayDurationField;
        
        private System.Nullable<double> modifiedDurationField;
        
        private System.Nullable<double> convexityField;
        
        private System.Nullable<double> percent_CouponRate_KField;
        
        private string couponTypeField;
        
        private System.Nullable<double> tHB_CurrentParField;
        
        private string xIPeriodField;
        
        private System.Nullable<int> frequencyPaymentField;
        
        private System.Nullable<double> yr_TTMField;
        
        private System.Nullable<System.DateTime> callPutDateField;
        
        private System.Nullable<double> percent_RealYieldField;
        
        private System.Nullable<double> indexRatioField;
        
        private System.Nullable<double> tHB_SettlementAmountField;
        
        private System.Nullable<double> percent_Unadjusted_GrossPriceField;
        
        private System.Nullable<double> percent_Unadjusted_CleanPriceField;
        
        private System.Nullable<double> percent_Unadjusted_AIField;
        
        private System.Nullable<double> tHB_Unadjusted_ParField;
        
        private string calc_RemarkField;
        
        /// <remarks/>
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SettlementDate {
            get {
                return this.settlementDateField;
            }
            set {
                this.settlementDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TradeDateAndTime {
            get {
                return this.tradeDateAndTimeField;
            }
            set {
                this.tradeDateAndTimeField = value;
            }
        }
        
        /// <remarks/>
        public int Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Percent_Yield {
            get {
                return this.percent_YieldField;
            }
            set {
                this.percent_YieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Percent_YS {
            get {
                return this.percent_YSField;
            }
            set {
                this.percent_YSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Percent_DM {
            get {
                return this.percent_DMField;
            }
            set {
                this.percent_DMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Percent_GrossPrice {
            get {
                return this.percent_GrossPriceField;
            }
            set {
                this.percent_GrossPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Percent_CleanPrice {
            get {
                return this.percent_CleanPriceField;
            }
            set {
                this.percent_CleanPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Percent_AI {
            get {
                return this.percent_AIField;
            }
            set {
                this.percent_AIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> THB_GrossValue {
            get {
                return this.tHB_GrossValueField;
            }
            set {
                this.tHB_GrossValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> THB_CleanValue {
            get {
                return this.tHB_CleanValueField;
            }
            set {
                this.tHB_CleanValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> THB_AIValue {
            get {
                return this.tHB_AIValueField;
            }
            set {
                this.tHB_AIValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> DSC {
            get {
                return this.dSCField;
            }
            set {
                this.dSCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> DCS {
            get {
                return this.dCSField;
            }
            set {
                this.dCSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Percent_I {
            get {
                return this.percent_IField;
            }
            set {
                this.percent_IField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> PVBP {
            get {
                return this.pVBPField;
            }
            set {
                this.pVBPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Yr_MacaulayDuration {
            get {
                return this.yr_MacaulayDurationField;
            }
            set {
                this.yr_MacaulayDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> ModifiedDuration {
            get {
                return this.modifiedDurationField;
            }
            set {
                this.modifiedDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Convexity {
            get {
                return this.convexityField;
            }
            set {
                this.convexityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Percent_CouponRate_K {
            get {
                return this.percent_CouponRate_KField;
            }
            set {
                this.percent_CouponRate_KField = value;
            }
        }
        
        /// <remarks/>
        public string CouponType {
            get {
                return this.couponTypeField;
            }
            set {
                this.couponTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> THB_CurrentPar {
            get {
                return this.tHB_CurrentParField;
            }
            set {
                this.tHB_CurrentParField = value;
            }
        }
        
        /// <remarks/>
        public string XIPeriod {
            get {
                return this.xIPeriodField;
            }
            set {
                this.xIPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FrequencyPayment {
            get {
                return this.frequencyPaymentField;
            }
            set {
                this.frequencyPaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Yr_TTM {
            get {
                return this.yr_TTMField;
            }
            set {
                this.yr_TTMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CallPutDate {
            get {
                return this.callPutDateField;
            }
            set {
                this.callPutDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Percent_RealYield {
            get {
                return this.percent_RealYieldField;
            }
            set {
                this.percent_RealYieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> IndexRatio {
            get {
                return this.indexRatioField;
            }
            set {
                this.indexRatioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> THB_SettlementAmount {
            get {
                return this.tHB_SettlementAmountField;
            }
            set {
                this.tHB_SettlementAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Percent_Unadjusted_GrossPrice {
            get {
                return this.percent_Unadjusted_GrossPriceField;
            }
            set {
                this.percent_Unadjusted_GrossPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Percent_Unadjusted_CleanPrice {
            get {
                return this.percent_Unadjusted_CleanPriceField;
            }
            set {
                this.percent_Unadjusted_CleanPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Percent_Unadjusted_AI {
            get {
                return this.percent_Unadjusted_AIField;
            }
            set {
                this.percent_Unadjusted_AIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> THB_Unadjusted_Par {
            get {
                return this.tHB_Unadjusted_ParField;
            }
            set {
                this.tHB_Unadjusted_ParField = value;
            }
        }
        
        /// <remarks/>
        public string Calc_Remark {
            get {
                return this.calc_RemarkField;
            }
            set {
                this.calc_RemarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ws1.thaibma.or.th/")]
    public partial class CalculationOutput {
        
        private CalcResult calcResultField;
        
        private CalcError calcErrorField;
        
        private ServiceError serviceResultField;
        
        /// <remarks/>
        public CalcResult CalcResult {
            get {
                return this.calcResultField;
            }
            set {
                this.calcResultField = value;
            }
        }
        
        /// <remarks/>
        public CalcError CalcError {
            get {
                return this.calcErrorField;
            }
            set {
                this.calcErrorField = value;
            }
        }
        
        /// <remarks/>
        public ServiceError ServiceResult {
            get {
                return this.serviceResultField;
            }
            set {
                this.serviceResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ws1.thaibma.or.th/")]
    public partial class BondFactor {
        
        private string symbolField;
        
        private bool isReOpen_BOTFRNField;
        
        private bool isILBField;
        
        private bool isYield2PriceField;
        
        private System.Nullable<System.DateTime> settlementDateField;
        
        private System.Nullable<System.DateTime> tradeDateAndTimeField;
        
        private System.Nullable<double> yieldField;
        
        private System.Nullable<YieldType> yieldTypeField;
        
        private bool isCallPutOptionField;
        
        private System.Nullable<System.DateTime> optionDateField;
        
        private int unitField;
        
        private System.Nullable<double> percent_PriceField;
        
        private System.Nullable<PriceType> priceTypeField;
        
        /// <remarks/>
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public bool isReOpen_BOTFRN {
            get {
                return this.isReOpen_BOTFRNField;
            }
            set {
                this.isReOpen_BOTFRNField = value;
            }
        }
        
        /// <remarks/>
        public bool isILB {
            get {
                return this.isILBField;
            }
            set {
                this.isILBField = value;
            }
        }
        
        /// <remarks/>
        public bool isYield2Price {
            get {
                return this.isYield2PriceField;
            }
            set {
                this.isYield2PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SettlementDate {
            get {
                return this.settlementDateField;
            }
            set {
                this.settlementDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TradeDateAndTime {
            get {
                return this.tradeDateAndTimeField;
            }
            set {
                this.tradeDateAndTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Yield {
            get {
                return this.yieldField;
            }
            set {
                this.yieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<YieldType> YieldType {
            get {
                return this.yieldTypeField;
            }
            set {
                this.yieldTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool isCallPutOption {
            get {
                return this.isCallPutOptionField;
            }
            set {
                this.isCallPutOptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> OptionDate {
            get {
                return this.optionDateField;
            }
            set {
                this.optionDateField = value;
            }
        }
        
        /// <remarks/>
        public int Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Percent_Price {
            get {
                return this.percent_PriceField;
            }
            set {
                this.percent_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<PriceType> PriceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ws1.thaibma.or.th/")]
    public enum YieldType {
        
        /// <remarks/>
        YTM,
        
        /// <remarks/>
        YS,
        
        /// <remarks/>
        DM,
        
        /// <remarks/>
        LastExe,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ws1.thaibma.or.th/")]
    public enum PriceType {
        
        /// <remarks/>
        Clean,
        
        /// <remarks/>
        Gross,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BondCalculationCompletedEventHandler(object sender, BondCalculationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BondCalculationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BondCalculationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CalculationOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CalculationOutput)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591