DROP TABLE OPICINF.KKB_TB_PROCESS_DATE CASCADE CONSTRAINTS;

CREATE TABLE OPICINF.KKB_TB_PROCESS_DATE
(
  PROC_DATE       DATE                          NOT NULL,
  NEXT_PROC_DATE  DATE,
  PREV_PROC_DATE  DATE,
  MODIFYDATE      DATE,
  MODIFYBY        NVARCHAR2(100)
)
TABLESPACE INFDATATBS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
